sudo: required
services:
        - docker

before_install:
        - docker build -t alexalex99922/react-test -f ./client/Dockerfile.dev ./client

script: 
        - docker run alexalex99922/react-test npm test

after_success:
        - docker build -t alexalex99922/multi-client ./client
        - docker build -t alexalex99922/multi-nginx ./nginx
        - docker build -t alexalex99922/multi-server ./server
        - docker build -t alexalex99922/multi-worker ./worker

#take those images and push them to docker hub

        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push alexalex99922/multi-client
        - docker push alexalex99922/multi-nginx
        - docker push alexalex99922/multi-server
        - docker push alexalex99922/multi-worker

deploy:
        provider: elasticbeanstalk
        region: us-east-2
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-2-566289283871
        bucket_path: docker-multi
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: $AWS_SECRET_KEY
